#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# comNET GmbH - Fabian Binder

def bake_elasticsearch(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(cmk.paths.local_agents_dir + "/plugins/elasticsearch", plugins_dir + "/elasticsearch")
    f = file(conf_dir + "/elasticsearch.cfg", "w")
    f.write(agent_file_header)
    if conf[0] == "static":
        f.write(pprint.pformat(conf[1]))

bakery_info["elasticsearch"] = {
    "bake_function" : bake_elasticsearch,
    "os"            : [ "linux", ],
    "verify_python" : True, # preinstall scripts ensure python is available and not python 3.x
}
