#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Copyright (C) 2017 comNET GmbH
#
# This file is part of check_elasticsearch.
# 
# check_elasticsearch is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Foobar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with check_elasticsearch.  If not, see <http://www.gnu.org/licenses/>.

# Changelog:
# 2017-10-25, comNET GmbH, Fabian Binder

def agent_elasticsearch_arguments(params, hostname, ipaddress):

    args = ''

    if 'piggyback' in params:
        args += ' -p ' + quote_shell_string(params['piggyback'])

    if 'port' in params:
        args += ' -P ' + str(params['port'])

    if 'infos' in params:
        args += " -i " + ",".join(params["infos"])

    if 'hosts' in params and params['hosts'] != []:
        for host in params['hosts']:
            args += " " + quote_shell_string(host)
    elif ipaddress:
        args += " " + quote_shell_string(ipaddress)
    else:
        args += " " + quote_shell_string(hostname)

    return args

special_agent_info['elasticsearch'] = agent_elasticsearch_arguments
