#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Copyright (C) 2017 comNET GmbH
#
# This file is part of check_elasticsearch.
# 
# check_elasticsearch is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Foobar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with check_elasticsearch.  If not, see <http://www.gnu.org/licenses/>.

# Changelog:
# Fabian Binder - comNET GmbH - 2017-05-31

def inventory_elasticsearch_shards(info):
    return [ (None, None) ]

def check_elasticsearch_shards(_no_item, params, info):
    total, successful, failed = map(int, info[0])
    state = 0
    message = "%s total shards, %s allocated, %s failed" % (total, successful, failed)
    if params:
        warn, crit = params["failed"]
        if type(warn) == float:
            warn = int(round(warn / 100.0 * total))
            crit = int(round(crit / 100.0 * total))
        if failed >= crit:
            state = 2
        elif failed >= warn:
            state = 1
        message += " (warn/crit at %s/%s failed shards)" % (warn, crit)

    return state, message

check_info["elasticsearch_shards"]  = {
    "check_function"     : check_elasticsearch_shards,
    "inventory_function" : inventory_elasticsearch_shards,
    "service_description": "Elasticsearch Shards",
    "has_perfdata"       : True,
    "group"              : "elasticsearch_shards",
}
